Resourses:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      - !Ref InstanceSecurityGroup
    KeyName: CD_demo
    ImageId: ""
  
    InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          cidrIp: 0.0.0.0/0