version: 2.1
commands: # a resuable command with parameters
  destroy_environment:
    steps: 
    - run:
        name: Destroy environment
        command: |
          aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  smoke_test:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: simulate error.
          command: |
            return 1   #simulate an error, cause the job to fail
      - destroy_environment
        when: on_fail
                   
workflows:
  welcome_workflow_name:
    jobs:
      - smoke_test