version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create_stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name prod-${CIRCLE_WORKFLOW_ID} \
              --parameter-overrides NAME=prod-${CIRCLE_WORKFLOW_ID}
              --capabilities "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
workflows:
  welcome_workflow_name:
    jobs:
      - create_infrastructure