version: 2.1
commands: # a resuable command with parameters
  print_pipeline_id:
    parameters:
      id:
        type: string
      steps:
        - run: echo <<parameters.id>>

jobs:
  pipeline_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          id: <<pipeline.id>>
                   
workflows:
  welcome_workflow_name:
    jobs:
      - pipeline_id