version: 2.1

jobs:
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test.
          command: |
            if curl -s --head "https://google.com" 
            then
              return 0
            else
              return 1
            fi
                   
workflows:
  welcome_workflow_name:
    jobs:
      - smoke_test